name: Build Docker image and deploy to Digital Ocean 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - name: Checkout master
      uses: actions/checkout@main

    # Install doctl.
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    # Add secrets to Dockefile
    - name: Inject Dockerfile secrets
      run: |
        cd wagops 
        sed -i 's/admin_superuser/${{ secrets.ADMIN_SUPERUSER}}/' Dockerfile
        sed -i 's/admin_email/${{ secrets.ADMIN_EMAIL}}/' Dockerfile
        sed -i 's/admin_password/${{ secrets.ADMIN_PASSWORD}}/' Dockerfile

    # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
    - name: Build container image
      run: |
        docker build -t registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/wagops:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: |
        doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/wagops:$(echo $GITHUB_SHA | head -c7)
